ALTER TABLE `glpi_plugin_metademands_tasks` CHANGE `formatastable` `formatastable` tinyint NOT NULL DEFAULT 1;
ALTER TABLE `glpi_plugin_metademands_configs` CHANGE `use_draft` `use_draft` tinyint DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_metademands` CHANGE `create_one_ticket` `create_one_ticket` tinyint NOT NULL DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `additional_number_day` `additional_number_day` int DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `display_type` `display_type` int DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `fields_link` `fields_link` varchar(255) NOT NULL DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `hidden_link` `hidden_link` varchar(255) NOT NULL DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `hidden_block` `hidden_block` varchar(255) NOT NULL DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `link_to_user` `link_to_user` int DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `use_date_now` `use_date_now` tinyint DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_fields` CHANGE `used_by_child` `used_by_child` tinyint DEFAULT 0;
ALTER TABLE `glpi_plugin_metademands_drafts_values` ADD `value2` text NOT NULL;
ALTER TABLE `glpi_plugin_metademands_tickets_fields` ADD `value2` text COLLATE utf8mb4_unicode_ci DEFAULT NULL;